
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author shrut
 */
public class Student_Description extends javax.swing.JFrame {

    /**
     * Creates new form Student_Description
     */
    public Student_Description() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Student ID", "Age", "Gender"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Short.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 49, 435, 334));

        jLabel1.setText("Student ID :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 72, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 218, -1, -1));

        jLabel2.setText(" ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 151, -1, -1));

        jLabel4.setText("Age :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 179, -1, -1));

        jLabel5.setText("Gender :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 282, -1, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 165, 306, 53));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 58, 306, 53));

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 472, -1, -1));

        jButton2.setText("Modify");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 472, -1, -1));

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 472, -1, -1));

        jButton3.setText("View Table");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 472, -1, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 343, 306, 53));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Female", "Male", "Others" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 265, 306, 59));

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Student ");
        jMenu2.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu2MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Student_Description");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Skills");
        jMenu4.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu4MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Carrer_Status");
        jMenu5.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu5MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    @SuppressWarnings("ConvertToTryWithResources")
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try 
	  {
              DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
         
                // Connect to Oracle Database
                Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE" ,"shruthi","kovvurss");
   
                Statement statement = con.createStatement();

                // Execute a SELECT query on Oracle Dummy DUAL Table. Useful for retrieving system values
                // Enables us to retrieve values as if querying from a table
                String query = "INSERT INTO STUDENT_DESCRIPTION VALUES(" + "'"+jTextField4.getText() + "',"+"'"+ jTextField2.getText()+"',"+"'"+ jTextField5.getText()+"'" +")";
                //String sqlqry="insert into customers values()"
                ResultSet rs = statement.executeQuery(query);
                
                JOptionPane.showMessageDialog(new JFrame(), "Inserted Successfully", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);

                rs.close();
                statement.close();
                con.close();
                
              

      } 
	  
	  catch(HeadlessException | SQLException e)
	  {
		  System.out.println(e);
	  }
        // TODO add your handling code here:

        
    }//GEN-LAST:event_jButton1ActionPerformed

    @SuppressWarnings("ConvertToTryWithResources")
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         try 
	  {
              if(jTable1.getRowCount()==0)
              {
             JOptionPane.showMessageDialog(this, "Please load the table", "Notice", JOptionPane.INFORMATION_MESSAGE);

              }
              
              else
              {
             // Load Oracle JDBC Driver
              int r = jTable1.getSelectedRow();
              
              if(r<0)
              {
                  JOptionPane.showMessageDialog(this, "Please select single Row For Update..", "Notice", JOptionPane.INFORMATION_MESSAGE);
              }
              else
              {
              DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
         
                // Connect to Oracle Database
                Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE" ,"shruthi","kovvurss");
   
                Statement statement = con.createStatement();

               
                String query = "UPDATE STUDENT_DESCRIPTION SET AGE=" +"'"+ jTextField2.getText() +"', GENDER ="+" '"+ jTextField5.getText() +"' WHERE SID =+" + jTextField4.getText();
                ResultSet rs = statement.executeQuery(query);
                JOptionPane.showMessageDialog(new JFrame(), "Upadated Successfully", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);

                rs.close();
                statement.close();
                con.close();
              } 
              }

      } 
	  
	  catch(HeadlessException | SQLException e)
	  {
		  System.out.println(e);
	  }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    @SuppressWarnings("ConvertToTryWithResources")
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         try 
	  {
              if(jTable1.getRowCount()==0)
              {
             JOptionPane.showMessageDialog(this, "Please load the table", "Notice", JOptionPane.INFORMATION_MESSAGE);

              }
              
              else
              {
             // Load Oracle JDBC Driver
              int r = jTable1.getSelectedRow();
              
              if(r<0)
              {
                  JOptionPane.showMessageDialog(this, "Please select single Row For Deleting..", "Notice", JOptionPane.INFORMATION_MESSAGE);
              }
              else
              {
              DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
         
                // Connect to Oracle Database
                Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE" ,"shruthi","kovvurss");
   
                Statement statement = con.createStatement();

                // Execute a SELECT query on Oracle Dummy DUAL Table. Useful for retrieving system values
                // Enables us to retrieve values as if querying from a table
                String query = "DELETE from STUDENT_DESCRIPTION where sid =  '" + jTextField4.getText() + "'"; 
                //String sqlqry="insert into customers values()"
                ResultSet rs = statement.executeQuery(query);
                
                JOptionPane.showMessageDialog(new JFrame(), "Deleted Successfully", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);

                /*while(rs.next()) {

                    //Date currentDate = rs.getDate(1); // get first column returned
                    //System.out.println("Current Date from Oracle is : "+currentDate);
                    System.out.println(rs.getString("ID") + rs.getString("AADHAR"));
                }*/
                rs.close();
                statement.close();
                con.close();
              } 
              
              }
      } 
	  
	  catch(HeadlessException | SQLException e)
	  {
		  System.out.println(e);
	  }

    }//GEN-LAST:event_jButton4ActionPerformed

    @SuppressWarnings("ConvertToTryWithResources")
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 try 
	  {
              DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
         
                // Connect to Oracle Database
               Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE" ,"shruthi","kovvurss");
                Statement statement = con.createStatement();

                // Execute a SELECT query on Oracle Dummy DUAL Table. Useful for retrieving system values
                // Enables us to retrieve values as if querying from a table
               /// String query = "UPDATE INTO STUDENT VALUES(" + "'"+jTextField2.getText() + "',"+"'"+ jTextField3.getText()+"'" +")";
                //String sqlqry="insert into customers values()"
                 //String query = "UPDATE student   SET  Sname='" + jTextField3.getText() + "'  WHERE sid ='" + jTextField2.getText() +"'";
                String query = "SELECT * FROM STUDENT_DESCRIPTION";
                ResultSet rs = statement.executeQuery(query);
                
                DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
               
                              
                model.setRowCount(0);
                
                while(rs.next()) 
                {                      
                    model.addRow(new Object[]{ rs.getString("SID"), rs.getString("AGE"),rs.getString("GENDER") });
                }
                 //ResultSet rs = statement.executeQuery(query);
                
                //JOptionPane.showMessageDialog(new JFrame(), "Updated Successfully", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);

                /*while(rs.next()) {

                    //Date currentDate = rs.getDate(1); // get first column returned
                    //System.out.println("Current Date from Oracle is : "+currentDate);
                    System.out.println(rs.getString("ID") + rs.getString("AADHAR"));
                }*/
                rs.close();
                statement.close();
                con.close();
                
              

      } 
	  
	  catch(SQLException e)
	  {
		  System.out.println(e);
	  }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenu2MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu2MenuSelected
        Student d = new Student();
        d.show();
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2MenuSelected

    private void jMenu4MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu4MenuSelected
        Skills d = new Skills();
        d.show();
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4MenuSelected

    private void jMenu5MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu5MenuSelected
           Carrer_Status d = new Carrer_Status();
        d.show();
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5MenuSelected

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
         String SelectedValue =jComboBox1.getSelectedItem().toString();
        jTextField5.setText(SelectedValue);

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        int rowindex = jTable1.getSelectedRow();
        
        //jComboBox1 j = new jComboBox();
        jTextField4.setText(model.getValueAt(rowindex,0).toString());
        jTextField2.setText(model.getValueAt(rowindex,1).toString());
        jTextField5.setText(model.getValueAt(rowindex,2).toString());        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Description.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Description.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Description.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Description.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Student_Description().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
